trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'messaging-patterns - Blob Processor - BUILD'
  
variables:
  vmImageName: 'ubuntu-latest'
  azureSubscription: 'Demo Account'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'API-CI'
    azureSubscription: ${{ variables.azureSubscription }}
    functionAppName: 'rutzsco-messaging-patterns-blob-processor'
    resourceGroupName: 'rutzsco-messaging-pattern'
    storageAccountName: 'rutzscoazfblobpro'
    region: 'East US'
    packageName: 'Demo.BlobProcessor.zip'
