apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-rabbitmq
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://guest:guest@RabbitMQ:5672"
  - name: durable
    value: true
scopes:
  - telemetrysimulator
  - datacollector