trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Services/function-service-bus/*

pool:
  vmImage: 'ubuntu-latest'
  rootDirectory: 'Services/durable-function-async-api'

variables:
  buildConfiguration: 'Release'

steps:

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(rootDirectory)/Infrastructure'
    artifact: 'Infrastructure'
    publishLocation: 'pipeline'
