parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: ''
- name: functionAppName
  default: ''
- name: functionAppStorageName
  default: ''
- name: packageName
  default: ''  

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: $(azureServiceConnection)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.region }} 
                az deployment group create --resource-group ${{ parameters.resourceGroupName }} --template-file $(templateFile) --parameters functionAppName=$(functionAppName) functionAppStorageName=$(functionAppStorageName) > outputs.json
