trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Services/function-service-bus/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'Infrastructure'
    artifact: 'Infrastructure'
    publishLocation: 'pipeline'
